@url = http://localhost:3001/
###
GET {{url}}api/persons

###
GET {{url}}info

###

GET {{url}}api/persons/6430fa2ee6e2db59994aef30


###
PUT {{url}}api/persons/6430fa2ee6e2db59994aef30
Content-Type: application/json

{
    "name": "Eddi Vedderrrr2",
    "number": "333-4223"
}

###
DELETE {{url}}api/persons/6430d12396c1dcaa947fafec

###
POST {{url}}api/persons
Content-Type: application/json

{
    "name": "Luigi Egas Layos",
    "number": "12384123-2389"
}